# Homework Assignment 1

In [1]:
import numpy as np

#### Problem 2. Evaluate the below algebraic expressions.

In [6]:
# Problem 0 - example
A = np.array([[1, 2], [3, 4]])
B = np.array([[1, 0], [0, 1]])
sol = A + B
print(sol)

[[2 2]
 [3 5]]


In [7]:
# Problem 2 (a)
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[5, 1, 3], [3, 2, 2]])
ans2a = A+B
print('answer : ')
print(ans2a)

answer : 
[[6 3 6]
 [7 7 8]]


In [8]:
# Problem 2 (b)
A = np.array([[3, 1, 3], [1, 2, 2]])
B = np.array([[8, 2, 2], [4, 4, 6]])
ans2b = 2*A - 0.5*B
print('answer : ')
print(ans2b)

answer : 
[[2. 1. 5.]
 [0. 2. 1.]]


In [9]:
# Problem 2 (c)
A = np.array([[3, 1, 3], [1, 2, 3]])
B = np.array([[1, 5, 3], [5, 4, 1]])
ans2c = 0.5*(A+B)
print('answer : ')
print(ans2c)

answer : 
[[2. 3. 3.]
 [3. 3. 2.]]


In [11]:
# Problem 2 (d)
A = np.array([[3, 1, 2], [3, 2, 4]])
B = np.array([[1, 1, 0], [2, 0, 1]])
transB = np.transpose(B)
ans2d = A.dot(transB)
print('answer : ')
print(ans2d)

answer : 
[[ 4  8]
 [ 5 10]]


In [12]:
# Problem 2 (e)
A = np.array([[1, 3, 2], [6, 4, 5], [9, 8, 7]])
ans2e = np.trace(A)
print('answer : ')
print(ans2e)

answer : 
12


In [13]:
# Problem 2 (f)
A = np.array([[3, 2], [-7, -5]])
ans2f = np.linalg.inv(A)
print('answer : ')
print(ans2f)

answer : 
[[ 5.  2.]
 [-7. -3.]]


In [14]:
# Problem 2 (g)
A = np.array([[1, -3, 5], [-1, 4, -5], [-1, 3, -6]])
ans2g = np.linalg.inv(A)
print('answer : ')
print(ans2g)

answer : 
[[ 9.  3.  5.]
 [ 1.  1.  0.]
 [-1. -0. -1.]]


In [16]:
# Problem 2 (h)
A = np.array([[1, 3], [3, 8]])
ans2h = np.linalg.det(A)
print('answer : ')
print(ans2h)

answer : 
-1.0000000000000004


In [11]:
# Problem 2 (i)


#### Problem 3. Solve the following systems of linear equations.

In [17]:
# Problem 3 (a)
# 2x + y = 5
# -x + 3y = 1
A = np.array([[2, 1], [-1, 3]])
B = np.array([5, 1])

ans3a = np.linalg.solve(A, B)
print(ans3a)
print("x = ", ans3a[0])
print("y = ", ans3a[1])

[2. 1.]
x =  2.0
y =  1.0


In [18]:
# Problem 3 (b)
# 5x + y - 2z = -4
# 2x + y + 5z = 1
# x - y + 2z = 1

A = np.array([[5, 1, -2], [2, 1, 5], [1, -1, 2]])
B = np.array([-4, 1, 1])

ans3b = np.linalg.solve(A, B)
print(ans3b)
print("x = ", ans3b[0])
print("y = ", ans3b[1])
print("z = ", ans3b[2])

[-0.5 -0.5  0.5]
x =  -0.5
y =  -0.5000000000000001
z =  0.5


#### Problem 6. Eigen value decomposition

In [19]:
# Problem 6 (a)
A = np.array([[-2, 3], [2, -1]])
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues:")
print(eigenvalues)
print("\nEigenvectors:")
print(eigenvectors)

Eigenvalues:
[-4.  1.]

Eigenvectors:
[[-0.83205029 -0.70710678]
 [ 0.5547002  -0.70710678]]


In [20]:
# Problem 6 (b)
A = np.array([[1, -2], [-2, 3]])
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues:")
print(eigenvalues)
print("\nEigenvectors:")
print(eigenvectors)

Eigenvalues:
[-0.23606798  4.23606798]

Eigenvectors:
[[-0.85065081  0.52573111]
 [-0.52573111 -0.85065081]]


In [21]:
# Problem 6 (c)
A = np.array([[5, 0], [3, -4]])
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues:")
print(eigenvalues)
print("\nEigenvectors:")
print(eigenvectors)

Eigenvalues:
[-4.  5.]

Eigenvectors:
[[0.         0.9486833 ]
 [1.         0.31622777]]


In [22]:
# Problem 6 (d)
A = np.array([[1, 2, 0], [0, 3, 0], [0, 1, 4]])
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues:")
print(eigenvalues)
print("\nEigenvectors:")
print(eigenvectors)

Eigenvalues:
[4. 1. 3.]

Eigenvectors:
[[ 0.          1.          0.57735027]
 [ 0.          0.          0.57735027]
 [ 1.          0.         -0.57735027]]
